services:
  wms-backend:
    build: ./backend
    container_name: wms-backend
    restart: always
    env_file:
      - backend/.env
    ports:
      - "3001:3001"

  wms-frontend:
    build:
      context: .
      args:
        BACKEND_URL: http://localhost:3001
        ENVIRONMENT: development
    container_name: wms-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - wms-backend
